-- matching 스키마 / RAW_GPS_LOG, CHARGE_TARGET (설계서 v1.3 기준)
-- 근거: doc/RUC_위치검증서버_테이블설계서_v1.3.docx §2.1, §2.2
-- 사용: psql -U postgres -d roadnet -f roadnet/sql/matching.sql

\c roadnet

CREATE SCHEMA IF NOT EXISTS MATCHING;
COMMENT ON SCHEMA MATCHING IS 'RUC 위치검증·과금 (설계서 v1.3)';

SET SEARCH_PATH TO MATCHING, PUBLIC;

-- §2.1 RAW_GPS_LOG – 원시 GPS 로그 (수집서버 INSERT)
-- 컬럼 순서: 설계서 v1.3 §2.1 표 순서
CREATE TABLE IF NOT EXISTS MATCHING.RAW_GPS_LOG (
    DEVICE_KEY      VARCHAR(36)     NOT NULL,
    GPS_DT          TIMESTAMP(0)    NOT NULL,
    GPS_SEQ         BIGINT          NOT NULL DEFAULT 0,
    TRIP_ID         VARCHAR(60)     NOT NULL,
    TRIP_EVENT      SMALLINT        NOT NULL DEFAULT 1,
    DRIVE_STATUS    SMALLINT        NOT NULL DEFAULT 0,
    GPS_LAT         NUMERIC(10, 6),
    MATCH_LAT       NUMERIC(10, 6),
    GPS_LON         NUMERIC(10, 6),
    MATCH_LON       NUMERIC(10, 6),
    INTERSECT_LEN   INTEGER         DEFAULT 0,
    RAW_VLD         BOOLEAN,
    SPEED_KMH       SMALLINT,
    HEADING         SMALLINT,
    ALTITUDE_M      SMALLINT,
    ACCURACY_M      SMALLINT,
    BATTERY         SMALLINT,
    RECV_DT         TIMESTAMP       NOT NULL DEFAULT NOW(),
    MATCH_STATUS    SMALLINT        NOT NULL DEFAULT 0,
    CONSTRAINT PK_RAW_GPS_LOG PRIMARY KEY (DEVICE_KEY, GPS_DT, GPS_SEQ),
    CONSTRAINT CK_RAW_GPS_LOG_TRIP_EVENT CHECK (TRIP_EVENT IN (0, 1, 2)),
    CONSTRAINT CK_RAW_GPS_LOG_DRIVE_STATUS CHECK (DRIVE_STATUS IN (0, 1, 2, 3)),
    CONSTRAINT CK_RAW_GPS_LOG_MATCH_STATUS CHECK (MATCH_STATUS IN (0, 1, 2, 3, 4))
);

COMMENT ON TABLE MATCHING.RAW_GPS_LOG IS '모바일 APP 원시 GPS. 위치검증서버가 PENDING(0) 조회 후 MATCHED(1) 갱신';
COMMENT ON COLUMN MATCHING.RAW_GPS_LOG.DEVICE_KEY IS 'PK, Client Key. ThreadPool sticky hash key';
COMMENT ON COLUMN MATCHING.RAW_GPS_LOG.GPS_DT IS 'PK, GPS 측정 시각 KST (timestamp(0) 초단위, rawgps_update 초단위 매칭)';
COMMENT ON COLUMN MATCHING.RAW_GPS_LOG.GPS_SEQ IS 'PK, 운행마다 1~N 초기화';
COMMENT ON COLUMN MATCHING.RAW_GPS_LOG.TRIP_ID IS 'INDEX, {DEVICE_KEY}_{YYYYMMDDHH24MISS} (수집서버 START 시 적재)';
COMMENT ON COLUMN MATCHING.RAW_GPS_LOG.TRIP_EVENT IS '0:START, 1:NONE, 2:END';
COMMENT ON COLUMN MATCHING.RAW_GPS_LOG.DRIVE_STATUS IS '0:ON_ROAD, 1:IDLE, 2:PARKED, 3:TUNNELING';
COMMENT ON COLUMN MATCHING.RAW_GPS_LOG.GPS_LAT IS '위도 WGS-84. NULL 허용. NUMERIC(10,6) 소수 6자리';
COMMENT ON COLUMN MATCHING.RAW_GPS_LOG.MATCH_LAT IS '맵매칭 위도 (위치검증서버 처리). NUMERIC(10,6) 소수 6자리';
COMMENT ON COLUMN MATCHING.RAW_GPS_LOG.GPS_LON IS '경도 WGS-84. NULL 허용. NUMERIC(10,6) 소수 6자리';
COMMENT ON COLUMN MATCHING.RAW_GPS_LOG.MATCH_LON IS '맵매칭 경도 (위치검증서버 처리). NUMERIC(10,6) 소수 6자리';
COMMENT ON COLUMN MATCHING.RAW_GPS_LOG.INTERSECT_LEN IS '매핑 교차 거리(m)';
COMMENT ON COLUMN MATCHING.RAW_GPS_LOG.RAW_VLD IS '원시 GPS 유효 여부. FALSE/NULL 이면 맵매칭 제외(SKIP)';
COMMENT ON COLUMN MATCHING.RAW_GPS_LOG.HEADING IS '방위각(정북 기준 시계방향 0~359도). smallint 정수, NULL 허용 (맵매칭 진행방향 판별)';
COMMENT ON COLUMN MATCHING.RAW_GPS_LOG.RECV_DT IS '수집서버 수신 시각';
COMMENT ON COLUMN MATCHING.RAW_GPS_LOG.MATCH_STATUS IS '0:PENDING, 1:MATCHED, 2:PROCESSING, 3:SKIP, 4:ERROR';

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = 'matching' AND TABLE_NAME = 'raw_gps_log' AND COLUMN_NAME = 'lat'
    ) THEN
        ALTER TABLE MATCHING.RAW_GPS_LOG RENAME COLUMN LAT TO GPS_LAT;
    END IF;
    IF EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = 'matching' AND TABLE_NAME = 'raw_gps_log' AND COLUMN_NAME = 'lon'
    ) THEN
        ALTER TABLE MATCHING.RAW_GPS_LOG RENAME COLUMN LON TO GPS_LON;
    END IF;
END $$;

ALTER TABLE MATCHING.RAW_GPS_LOG
    ALTER COLUMN GPS_LAT DROP NOT NULL,
    ALTER COLUMN GPS_LON DROP NOT NULL;

ALTER TABLE MATCHING.RAW_GPS_LOG
    ADD COLUMN IF NOT EXISTS MATCH_LAT NUMERIC(10, 6),
    ADD COLUMN IF NOT EXISTS MATCH_LON NUMERIC(10, 6),
    ADD COLUMN IF NOT EXISTS INTERSECT_LEN INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS RAW_VLD BOOLEAN;

ALTER TABLE MATCHING.RAW_GPS_LOG
    ALTER COLUMN GPS_LAT TYPE NUMERIC(10, 6),
    ALTER COLUMN GPS_LON TYPE NUMERIC(10, 6),
    ALTER COLUMN MATCH_LAT TYPE NUMERIC(10, 6),
    ALTER COLUMN MATCH_LON TYPE NUMERIC(10, 6);

ALTER TABLE MATCHING.RAW_GPS_LOG
    ALTER COLUMN SPEED_KMH DROP NOT NULL,
    ALTER COLUMN HEADING DROP NOT NULL,
    ALTER COLUMN ALTITUDE_M DROP NOT NULL,
    ALTER COLUMN ACCURACY_M DROP NOT NULL,
    ALTER COLUMN BATTERY DROP NOT NULL;

-- 소수 무의미 컬럼 정수화(기존 DB 마이그레이션): SPEED_KMH/ALTITUDE_M/ACCURACY_M → SMALLINT
ALTER TABLE MATCHING.RAW_GPS_LOG
    ALTER COLUMN SPEED_KMH  TYPE SMALLINT USING ROUND(SPEED_KMH)::SMALLINT,
    ALTER COLUMN ALTITUDE_M TYPE SMALLINT USING ROUND(ALTITUDE_M)::SMALLINT,
    ALTER COLUMN ACCURACY_M TYPE SMALLINT USING ROUND(ACCURACY_M)::SMALLINT;

CREATE INDEX IF NOT EXISTS IDX_RAW_GPS_LOG_DEVICE_KEY
    ON MATCHING.RAW_GPS_LOG (DEVICE_KEY);

CREATE INDEX IF NOT EXISTS IDX_RAW_GPS_LOG_TRIP_ID
    ON MATCHING.RAW_GPS_LOG (TRIP_ID);

CREATE INDEX IF NOT EXISTS IDX_RAW_GPS_LOG_PENDING
    ON MATCHING.RAW_GPS_LOG (DEVICE_KEY, TRIP_ID, GPS_DT, GPS_SEQ)
    WHERE MATCH_STATUS = 0;

CREATE INDEX IF NOT EXISTS IDX_RAW_GPS_LOG_DEVICE_MATCHED
    ON MATCHING.RAW_GPS_LOG (DEVICE_KEY, GPS_DT DESC)
    WHERE MATCH_STATUS = 1;

-- §2.2 CHARGE_TARGET – 과금 대상 통합 (위치검증서버 INSERT)
CREATE TABLE IF NOT EXISTS MATCHING.CHARGE_TARGET (
    TRIP_ID             VARCHAR(60)     NOT NULL,
    DEVICE_KEY          VARCHAR(36)     NOT NULL,
    TRIP_SEQ            INTEGER         NOT NULL DEFAULT 0,
    CHARGE_TYPE         VARCHAR(20)     NOT NULL,
    CHARGE_UNIT         VARCHAR(10)     NOT NULL,
    LINK_ID             VARCHAR(20),
    FROM_ID             VARCHAR(20)     NOT NULL,
    TO_ID               VARCHAR(20)     NOT NULL,
    FROM_LAT            NUMERIC(10, 6)  NOT NULL DEFAULT 0,
    FROM_LON            NUMERIC(10, 6)  NOT NULL DEFAULT 0,
    TO_LAT              NUMERIC(10, 6)  NOT NULL DEFAULT 0,
    TO_LON              NUMERIC(10, 6)  NOT NULL DEFAULT 0,
    DIST_M              INTEGER         NOT NULL DEFAULT 0,
    SPEED_KMH           NUMERIC(6, 1)   NOT NULL DEFAULT 0,
    SPEED_LIMIT_KMH     NUMERIC(6, 1)   NOT NULL DEFAULT 0,
    STAY_SECONDS        INTEGER         NOT NULL DEFAULT 0,
    ZONE_ID             VARCHAR(20),
    ZONE_NAME           VARCHAR(100),
    OCCUR_DT            TIMESTAMP       NOT NULL,
    TRIP_START_DT       TIMESTAMP       NOT NULL,
    TRIP_END_DT         TIMESTAMP,
    CHARGE_STATUS       VARCHAR(20)     NOT NULL DEFAULT 'PENDING',
    REG_DT              TIMESTAMP       NOT NULL DEFAULT NOW(),
    UPD_DT              TIMESTAMP       NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_CHARGE_TARGET PRIMARY KEY (TRIP_ID, DEVICE_KEY),
    CONSTRAINT CK_CHARGE_TARGET_TYPE CHECK (CHARGE_TYPE IN ('NODE_STEP', 'OPEN_ROAD', 'CLOSED_ROAD', 'SPEED', 'PARKING')),
    CONSTRAINT CK_CHARGE_TARGET_UNIT CHECK (CHARGE_UNIT IN ('NODE', 'LINK')),
    CONSTRAINT CK_CHARGE_TARGET_STATUS CHECK (CHARGE_STATUS IN ('PENDING', 'PROCESSING', 'CHARGED', 'SKIP'))
);

COMMENT ON TABLE MATCHING.CHARGE_TARGET IS '과금 대상 통합. 1행=1과금항목. 위치검증서버 INSERT, 과금서버 READ';
COMMENT ON COLUMN MATCHING.CHARGE_TARGET.TRIP_ID IS 'PK, {DEVICE_KEY}_{YYYYMMDDHH24MISS} (수집서버 적재분)';
COMMENT ON COLUMN MATCHING.CHARGE_TARGET.TRIP_SEQ IS '동일 운행 내 항목 순번';
COMMENT ON COLUMN MATCHING.CHARGE_TARGET.CHARGE_TYPE IS 'NODE_STEP/OPEN_ROAD/CLOSED_ROAD/SPEED/PARKING';
COMMENT ON COLUMN MATCHING.CHARGE_TARGET.CHARGE_UNIT IS 'NODE / LINK';
COMMENT ON COLUMN MATCHING.CHARGE_TARGET.CHARGE_STATUS IS 'PENDING/PROCESSING/CHARGED/SKIP';

CREATE INDEX IF NOT EXISTS IDX_CHARGE_TARGET_PENDING
    ON MATCHING.CHARGE_TARGET (TRIP_START_DT, TRIP_ID)
    WHERE CHARGE_STATUS = 'PENDING';

ALTER TABLE MATCHING.CHARGE_TARGET
    ALTER COLUMN FROM_LAT TYPE NUMERIC(10, 6),
    ALTER COLUMN FROM_LON TYPE NUMERIC(10, 6),
    ALTER COLUMN TO_LAT TYPE NUMERIC(10, 6),
    ALTER COLUMN TO_LON TYPE NUMERIC(10, 6);

GRANT USAGE ON SCHEMA MATCHING TO MYTOBCOM;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA MATCHING TO MYTOBCOM;
ALTER DEFAULT PRIVILEGES IN SCHEMA MATCHING
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO MYTOBCOM;
