-- ROADNET DB / PRIM_LINK_INFO — 맵매칭 지도 도로선 (슬림)
-- 사용: psql -U postgres -d roadnet -f roadnet/sql/prim_map_create.sql
-- 적재: python3 roadnet/scripts/psf_load_prim_link_info.py

\c roadnet

-- GEOMETRY(LINESTRING,4326) 타입·ST_* 공간 함수 사용을 위해 PostGIS 활성화
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE SCHEMA IF NOT EXISTS ROADNET;
COMMENT ON SCHEMA ROADNET IS 'RUC 위치검증·과금·맵매칭 표시 (PRIM_*)';

SET SEARCH_PATH TO ROADNET, PUBLIC;

-- PRIM_LINK_INFO — PSF LINK_INFO 슬림 (지도 도로선 + MATCH_OFFSET_M M점)
CREATE TABLE IF NOT EXISTS ROADNET.PRIM_LINK_INFO (
    -- PK
    LINK_ID       VARCHAR(10)                  NOT NULL,
    -- 형상·길이 (M점 보간 핵심)
    LEN           NUMERIC(12, 3)               NOT NULL,
    GEOM          GEOMETRY(LINESTRING, 4326)   NOT NULL,
    -- 도로 속성 (PSF LINK_INFO_DATA)
    SPEED_LIMIT   SMALLINT,
    ROAD_RANK     SMALLINT,
    ROAD_CONNECT  SMALLINT,
    ROAD_TYPE     SMALLINT,
    LANES         SMALLINT,
    NAME          VARCHAR(46),
    -- 출발(시작) 노드 — f_node 방향
    ST_ND_ID      VARCHAR(10),
    ST_ND_NAME    VARCHAR(50),
    ST_ND_LON     NUMERIC(10, 6),
    ST_ND_LAT     NUMERIC(10, 6),
    -- 도착(종료) 노드 — t_node
    ED_ND_ID      VARCHAR(10),
    ED_ND_NAME    VARCHAR(50),
    ED_ND_LON     NUMERIC(10, 6),
    ED_ND_LAT     NUMERIC(10, 6),
    CONSTRAINT PK_PRIM_LINK_INFO PRIMARY KEY (LINK_ID),
    CONSTRAINT CK_PRIM_LINK_LEN CHECK (LEN >= 0)
);

COMMENT ON TABLE ROADNET.PRIM_LINK_INFO IS '지도 도로선·MATCH_OFFSET_M 기반 M점 표시 (슬림). 1 link_id = 1 LineString';
COMMENT ON COLUMN ROADNET.PRIM_LINK_INFO.LINK_ID IS 'PK. 링크 ID (10자리). PRIM_RAWGPS.MATCH_LINK_ID 가 참조';
COMMENT ON COLUMN ROADNET.PRIM_LINK_INFO.LEN IS 'f_node 방향 링크 길이(m). PSF dfLen. 0 이하이면 0 저장';
COMMENT ON COLUMN ROADNET.PRIM_LINK_INFO.GEOM IS '세그먼트를 len_from_link 순 ST_MakeLine 결합한 WGS84 LineString(EPSG:4326). 지도 남색 선·M점 보간 기준';
COMMENT ON COLUMN ROADNET.PRIM_LINK_INFO.SPEED_LIMIT IS '제한속도(km/h)';
COMMENT ON COLUMN ROADNET.PRIM_LINK_INFO.ROAD_RANK IS '도로 등급 (고속·국도·지방 등)';
COMMENT ON COLUMN ROADNET.PRIM_LINK_INFO.ROAD_CONNECT IS '연결로 여부 (0/1, 구코드 101~108)';
COMMENT ON COLUMN ROADNET.PRIM_LINK_INFO.ROAD_TYPE IS '시설 유형. (0=일반, 1=교량, 2=터널, 3=고가, 4=지하)';
COMMENT ON COLUMN ROADNET.PRIM_LINK_INFO.LANES IS '차로 수';
COMMENT ON COLUMN ROADNET.PRIM_LINK_INFO.NAME IS '도로명 (최대 46자)';
COMMENT ON COLUMN ROADNET.PRIM_LINK_INFO.ST_ND_ID IS '시작(출발) 노드 ID. PSF qwStNodeID / MOCT f_node';
COMMENT ON COLUMN ROADNET.PRIM_LINK_INFO.ST_ND_NAME IS '시작(출발) 노드 명칭. PSF에 없음 — ETL 시 network.moct_node.node_name 조인. NULL·빈값 가능';
COMMENT ON COLUMN ROADNET.PRIM_LINK_INFO.ST_ND_LON IS '시작 노드 경도 WGS84. PSF dwStNodeX/360000.0 또는 GEOM 첫 점';
COMMENT ON COLUMN ROADNET.PRIM_LINK_INFO.ST_ND_LAT IS '시작 노드 위도 WGS84. PSF dwStNodeY/360000.0 또는 GEOM 첫 점';
COMMENT ON COLUMN ROADNET.PRIM_LINK_INFO.ED_ND_ID IS '종료(도착) 노드 ID. PSF qwEdNodeID / MOCT t_node';
COMMENT ON COLUMN ROADNET.PRIM_LINK_INFO.ED_ND_NAME IS '종료(도착) 노드 명칭. PSF에 없음 — ETL 시 network.moct_node.node_name 조인. NULL·빈값 가능';
COMMENT ON COLUMN ROADNET.PRIM_LINK_INFO.ED_ND_LON IS '종료 노드 경도 WGS84. PSF dwEdNodeX/360000 또는 GEOM 끝 점';
COMMENT ON COLUMN ROADNET.PRIM_LINK_INFO.ED_ND_LAT IS '종료 노드 위도 WGS84. PSF dwEdNodeY/360000 또는 GEOM 끝 점';
COMMENT ON CONSTRAINT PK_PRIM_LINK_INFO ON ROADNET.PRIM_LINK_INFO IS '링크 ID 단일 PK';
COMMENT ON CONSTRAINT CK_PRIM_LINK_LEN ON ROADNET.PRIM_LINK_INFO IS 'LEN 음수 방지 (0 허용)';

-- INDEX① 공간 — trip bbox·주변 링크·GeoJSON 조회
CREATE INDEX IF NOT EXISTS IDX_PRIM_LINK_GEOM ON ROADNET.PRIM_LINK_INFO USING GIST (GEOM);

-- INDEX② 도로명 검색·팝업
CREATE INDEX IF NOT EXISTS IDX_PRIM_LINK_NAME ON ROADNET.PRIM_LINK_INFO (NAME);
