-- PRIM_RAWGPS PK·INDEX·컬럼순서 마이그레이션
-- 사용: psql -U postgres -d roadnet -f roadnet/sql/prim_rawgps_pk_index_migrate.sql
--
-- 사전 조건: (TRIP_ID, GPS_SEQ) 중복 0건
--   SELECT TRIP_ID, GPS_SEQ, COUNT(*) FROM ROADNET.PRIM_RAWGPS
--   GROUP BY TRIP_ID, GPS_SEQ HAVING COUNT(*) > 1;

\c roadnet

SET SEARCH_PATH TO ROADNET, PUBLIC;

-- 구 인덱스 제거
DROP INDEX IF EXISTS ROADNET.IDX_PRIM_RAWGPS_DEVICE_KEY;
DROP INDEX IF EXISTS ROADNET.IDX_PRIM_RAWGPS_TRIP_ID;
DROP INDEX IF EXISTS ROADNET.IDX_PRIM_RAWGPS_PENDING;
DROP INDEX IF EXISTS ROADNET.IDX_PRIM_RAWGPS_DEVICE_MATCHED;
DROP INDEX IF EXISTS ROADNET.IDX_PRIM_RAWGPS_DEVICE_TIME;

-- 컬럼 순서·PK 반영: 신규 테이블로 재적재
CREATE TABLE ROADNET.PRIM_RAWGPS_NEW (
    TRIP_ID         VARCHAR(60)     NOT NULL,
    GPS_SEQ         BIGINT          NOT NULL DEFAULT 0,
    DEVICE_KEY      VARCHAR(36)     NOT NULL,
    GPS_DT          CHAR(14)        NOT NULL,
    TRIP_EVENT      SMALLINT        NOT NULL DEFAULT 1,
    DRIVE_STATUS    SMALLINT        NOT NULL DEFAULT 0,
    GPS_LAT         NUMERIC(10, 6)  DEFAULT NULL,
    MATCH_LAT       NUMERIC(10, 6)  DEFAULT NULL,
    GPS_LON         NUMERIC(10, 6)  DEFAULT NULL,
    MATCH_LON       NUMERIC(10, 6)  DEFAULT NULL,
    INTERSECT_LEN   INTEGER         DEFAULT 0,
    RAW_VLD         BOOLEAN         DEFAULT FALSE,
    SPEED_KMH       SMALLINT        DEFAULT NULL,
    HEADING         SMALLINT        DEFAULT NULL,
    ALTITUDE_M      SMALLINT        DEFAULT NULL,
    ACCURACY_M      SMALLINT        DEFAULT NULL,
    BATTERY         SMALLINT        DEFAULT NULL,
    RECV_DT         CHAR(14)        NOT NULL DEFAULT TO_CHAR(NOW(), 'YYYYMMDDHH24MISS'),
    MATCH_STATUS    SMALLINT        NOT NULL DEFAULT 0,
    CONSTRAINT PK_PRIM_RAWGPS_NEW PRIMARY KEY (TRIP_ID, GPS_SEQ),
    CONSTRAINT CK_PRIM_RAWGPS_TRIP_EVENT CHECK (TRIP_EVENT IN (0, 1, 2)),
    CONSTRAINT CK_PRIM_RAWGPS_DRIVE_STATUS CHECK (DRIVE_STATUS IN (0, 1, 2, 3)),
    CONSTRAINT CK_PRIM_RAWGPS_MATCH_STATUS CHECK (MATCH_STATUS IN (0, 1, 2, 3, 4))
);

INSERT INTO ROADNET.PRIM_RAWGPS_NEW (
    TRIP_ID, GPS_SEQ, DEVICE_KEY, GPS_DT,
    TRIP_EVENT, DRIVE_STATUS,
    GPS_LAT, MATCH_LAT, GPS_LON, MATCH_LON,
    INTERSECT_LEN, RAW_VLD,
    SPEED_KMH, HEADING, ALTITUDE_M, ACCURACY_M, BATTERY,
    RECV_DT, MATCH_STATUS
)
SELECT
    TRIP_ID, GPS_SEQ, DEVICE_KEY, GPS_DT,
    TRIP_EVENT, DRIVE_STATUS,
    GPS_LAT, MATCH_LAT, GPS_LON, MATCH_LON,
    INTERSECT_LEN, RAW_VLD,
    SPEED_KMH, HEADING, ALTITUDE_M, ACCURACY_M, BATTERY,
    RECV_DT, MATCH_STATUS
FROM ROADNET.PRIM_RAWGPS;

DROP TABLE ROADNET.PRIM_RAWGPS;
ALTER TABLE ROADNET.PRIM_RAWGPS_NEW RENAME TO PRIM_RAWGPS;
ALTER TABLE ROADNET.PRIM_RAWGPS RENAME CONSTRAINT PK_PRIM_RAWGPS_NEW TO PK_PRIM_RAWGPS;

CREATE INDEX IDX_PRIM_RAWGPS_PENDING
    ON ROADNET.PRIM_RAWGPS (DEVICE_KEY, TRIP_ID, GPS_DT, GPS_SEQ)
    WHERE MATCH_STATUS = 0
      AND DRIVE_STATUS <> 1
      AND RAW_VLD IS TRUE;

CREATE INDEX IDX_PRIM_RAWGPS_DEVICE_TIME
    ON ROADNET.PRIM_RAWGPS (DEVICE_KEY, GPS_DT DESC);

COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.TRIP_ID IS 'PK-1, {DEVICE_KEY}_{YYYYMMDDHH24MISS}';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.GPS_SEQ IS 'PK-2, 운행(TRIP_ID)마다 1~N';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.DEVICE_KEY IS 'INDEX①·② 선두. ThreadPool sticky hash key';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.GPS_DT IS 'INDEX①·②. GPS 측정 시각 KST CHAR(14)';
