-- ROADNET DB / ROADNET 스키마 / 과금(개방형·폐쇄형·주정차) 기준정보·결과 (설계안, doc/README.txt H절 TODO#1)
-- 사용: psql -U postgres -d roadnet -f roadnet/sql/prim_charge_create.sql
-- 상세 판정 흐름: web/docs/charge-flow.html
--
-- 현재 맵매칭 구조와의 연결점:
--   PRIM_GATE_INFO.NODE_ID   → PRIM_LINK_INFO.ST_ND_ID/ED_ND_ID (표준노드링크 노드, NODE_TYPE_TG=105 톨게이트 포함)
--   PRIM_GATE_INFO.LINK_ID   → PRIM_LINK_INFO.LINK_ID (진입 중인 링크로도 판정 가능하도록 병행 보관)
--   PRIM_PARKING_ZONE.GEOM   → PRIM_LINK_INFO.GEOM 과 동일하게 PostGIS 사용 (이미 두 컬럼 다 활성화돼 있음)
--   PRIM_CHARGEHAND.TRIP_ID/DEVICE_KEY → PRIM_RAWGPS 조인키 패턴 그대로 재사용
--   ※ 기존 관례대로 하드 FK는 걸지 않음(PRIM_RAWGPS.MATCH_LINK_ID도 동일) — 조인키는 주석으로만 명시
--
-- 명명: SECTION_ID 대신 GATE_PAIR_ID 사용 — 기존 VEHICLE_TRIP_SESSION(트립 TTL 세션) 용어와의 혼동 방지
--   (doc/README.txt E절 참조)

\c roadnet

CREATE EXTENSION IF NOT EXISTS postgis;

SET SEARCH_PATH TO ROADNET, PUBLIC;

-- ---------------------------------------------------------------------------
-- PRIM_GATE_INFO — 개방형(OPEN) + 폐쇄형(CLOSED_ROAD: TOLL/SPEED 공용) 게이트 기준정보
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ROADNET.PRIM_GATE_INFO (
    -- PK
    GATE_ID           VARCHAR(20)     NOT NULL,
    -- 유형·목적
    GATE_TYPE         SMALLINT        NOT NULL,
    PURPOSE           SMALLINT        DEFAULT NULL,
    GATE_PAIR_ID      VARCHAR(20)     DEFAULT NULL,
    -- 위치 (표준노드링크/PRIM_LINK_INFO 참조)
    NODE_ID           VARCHAR(10)     DEFAULT NULL,
    LINK_ID           VARCHAR(10)     DEFAULT NULL,
    DIR_COND          SMALLINT        NOT NULL DEFAULT 0,
    -- 과금 기준값 (유형별로 해당 컬럼만 사용)
    FEE_AMOUNT        NUMERIC(10, 0)  DEFAULT NULL,
    FEE_PER_KM        NUMERIC(10, 2)  DEFAULT NULL,
    SPEED_LIMIT_KMH   SMALLINT        DEFAULT NULL,
    -- 운영
    GATE_NAME         VARCHAR(60)     DEFAULT NULL,
    USE_YN            BOOLEAN         NOT NULL DEFAULT TRUE,
    REG_DT            TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    UPD_DT            TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_PRIM_GATE_INFO PRIMARY KEY (GATE_ID),
    CONSTRAINT CK_PRIM_GATE_TYPE CHECK (GATE_TYPE IN (0, 1, 2)),
    CONSTRAINT CK_PRIM_GATE_PURPOSE CHECK (PURPOSE IS NULL OR PURPOSE IN (0, 1)),
    CONSTRAINT CK_PRIM_GATE_DIR_COND CHECK (DIR_COND IN (0, 1, 2)),
    -- OPEN(0)은 짝 없음 / CLOSED_IN·OUT(1,2)은 짝 필수 — 데이터 정합성 최소 보장
    CONSTRAINT CK_PRIM_GATE_PAIR_CONSISTENCY CHECK (
        (GATE_TYPE = 0 AND GATE_PAIR_ID IS NULL) OR
        (GATE_TYPE IN (1, 2) AND GATE_PAIR_ID IS NOT NULL)
    )
);

COMMENT ON TABLE ROADNET.PRIM_GATE_INFO IS
    '개방형(OPEN)·폐쇄형(CLOSED_ROAD: TOLL/SPEED) 게이트 기준정보. 테스트 시 표준노드링크의 TG 노드가 아닌 임의 노드도 등록 가능';
COMMENT ON COLUMN ROADNET.PRIM_GATE_INFO.GATE_ID IS 'PK. 게이트 식별자 (예: GT00000001)';
COMMENT ON COLUMN ROADNET.PRIM_GATE_INFO.GATE_TYPE IS '0:OPEN(개방형), 1:CLOSED_IN(폐쇄형 진입), 2:CLOSED_OUT(폐쇄형 진출)';
COMMENT ON COLUMN ROADNET.PRIM_GATE_INFO.PURPOSE IS
    '0:TOLL(통행료), 1:SPEED(구간단속). CLOSED_IN/OUT만 사용, OPEN은 NULL(정액이라 목적 구분 불필요)';
COMMENT ON COLUMN ROADNET.PRIM_GATE_INFO.GATE_PAIR_ID IS
    'CLOSED_IN/CLOSED_OUT 진입-진출 짝짓기 키. 같은 값을 가진 IN/OUT 한 쌍이 한 구간. OPEN은 NULL';
COMMENT ON COLUMN ROADNET.PRIM_GATE_INFO.NODE_ID IS
    '게이트 위치 노드 ID. PRIM_LINK_INFO.ST_ND_ID/ED_ND_ID 조인키(하드FK 미설정). 실서비스는 NODE_TYPE_TG=105 톨게이트 노드와 일치하는 것이 자연스러움';
COMMENT ON COLUMN ROADNET.PRIM_GATE_INFO.LINK_ID IS
    '게이트가 걸린 링크 ID. PRIM_LINK_INFO.LINK_ID 조인키. NODE_ID와 병행 보관(맵매칭 결과가 링크 단위로 오므로 링크 기준 판정도 가능하게)';
COMMENT ON COLUMN ROADNET.PRIM_GATE_INFO.DIR_COND IS '0:방향무관, 1:ST_ND→ED_ND 방향만 과금, 2:ED_ND→ST_ND 방향만 과금';
COMMENT ON COLUMN ROADNET.PRIM_GATE_INFO.FEE_AMOUNT IS 'OPEN 전용. 게이트 통과 시 정액 요금(원)';
COMMENT ON COLUMN ROADNET.PRIM_GATE_INFO.FEE_PER_KM IS 'CLOSED_IN·PURPOSE=TOLL 전용. 거리 단가(원/km). CLOSED_OUT 행엔 NULL(진입 게이트 값 사용)';
COMMENT ON COLUMN ROADNET.PRIM_GATE_INFO.SPEED_LIMIT_KMH IS 'CLOSED_IN·PURPOSE=SPEED 전용. 구간 제한속도(km/h). CLOSED_OUT 행엔 NULL';
COMMENT ON COLUMN ROADNET.PRIM_GATE_INFO.GATE_NAME IS '표시용 이름 (테스트 게이트 식별 용도)';
COMMENT ON COLUMN ROADNET.PRIM_GATE_INFO.USE_YN IS 'FALSE면 판정 대상에서 제외 — 삭제 대신 비활성화로 테스트 켜고 끄기';
COMMENT ON COLUMN ROADNET.PRIM_GATE_INFO.UPD_DT IS '최종 수정시각 — 인메모리 캐시 갱신 감지용(doc/README.txt F절)';

CREATE INDEX IF NOT EXISTS IDX_PRIM_GATE_NODE ON ROADNET.PRIM_GATE_INFO (NODE_ID) WHERE USE_YN IS TRUE;
CREATE INDEX IF NOT EXISTS IDX_PRIM_GATE_LINK ON ROADNET.PRIM_GATE_INFO (LINK_ID) WHERE USE_YN IS TRUE;
CREATE INDEX IF NOT EXISTS IDX_PRIM_GATE_PAIR ON ROADNET.PRIM_GATE_INFO (GATE_PAIR_ID) WHERE GATE_PAIR_ID IS NOT NULL;

-- ---------------------------------------------------------------------------
-- PRIM_PARKING_ZONE — 주정차 단속 구역 기준정보
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ROADNET.PRIM_PARKING_ZONE (
    ZONE_ID         VARCHAR(20)                NOT NULL,
    ZONE_NAME       VARCHAR(60)                DEFAULT NULL,
    GEOM            GEOMETRY(POLYGON, 4326)    NOT NULL,
    ALLOW_SECONDS   INTEGER                    NOT NULL DEFAULT 300,
    FINE_AMOUNT     NUMERIC(10, 0)             DEFAULT NULL,
    USE_YN          BOOLEAN                    NOT NULL DEFAULT TRUE,
    REG_DT          TIMESTAMPTZ                NOT NULL DEFAULT NOW(),
    UPD_DT          TIMESTAMPTZ                NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_PRIM_PARKING_ZONE PRIMARY KEY (ZONE_ID),
    CONSTRAINT CK_PRIM_PARKING_ALLOW_SEC CHECK (ALLOW_SECONDS >= 0)
);

COMMENT ON TABLE ROADNET.PRIM_PARKING_ZONE IS
    '주정차 금지구역 기준정보. PRIM_LINK_INFO.GEOM과 동일하게 PostGIS 폴리곤 사용 — 임의 지역 테스트 시 폴리곤만 새로 그리면 됨(링크 목록 관리 불필요)';
COMMENT ON COLUMN ROADNET.PRIM_PARKING_ZONE.ZONE_ID IS 'PK. 구역 식별자 (예: PZ00000001)';
COMMENT ON COLUMN ROADNET.PRIM_PARKING_ZONE.GEOM IS
    '금지구역 폴리곤 WGS84(EPSG:4326). 정차 시작좌표(GPS_LAT/LON 또는 MATCH_LAT/LON) 포함 여부는 ST_Contains로 판정';
COMMENT ON COLUMN ROADNET.PRIM_PARKING_ZONE.ALLOW_SECONDS IS '유예시간(초). 이내 정차는 무과금(NON_CHARGE_REASON=유예시간이내)';
COMMENT ON COLUMN ROADNET.PRIM_PARKING_ZONE.FINE_AMOUNT IS '유예시간 초과 시 과태료(원)';
COMMENT ON COLUMN ROADNET.PRIM_PARKING_ZONE.USE_YN IS 'FALSE면 판정 대상에서 제외';
COMMENT ON COLUMN ROADNET.PRIM_PARKING_ZONE.UPD_DT IS '최종 수정시각 — 인메모리 캐시 갱신 감지용';

CREATE INDEX IF NOT EXISTS IDX_PRIM_PARKING_GEOM ON ROADNET.PRIM_PARKING_ZONE USING GIST (GEOM) WHERE USE_YN IS TRUE;

-- ---------------------------------------------------------------------------
-- PRIM_CHARGEHAND — 과금 판정 결과 (OPEN·CLOSED_ROAD·PARKING 공통)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ROADNET.PRIM_CHARGEHAND (
    -- PK (PRIM_RAWGPS의 TRIP_ID·GPS_SEQ 패턴과 동일하게 트립 내 순번 사용)
    TRIP_ID             VARCHAR(60)     NOT NULL,
    CHARGE_SEQ          INTEGER         NOT NULL DEFAULT 1,
    -- 조인용 (INDEX① 패턴 재사용)
    DEVICE_KEY          VARCHAR(36)     NOT NULL,
    -- 유형
    CHARGE_TYPE         SMALLINT        NOT NULL,
    PURPOSE             SMALLINT        DEFAULT NULL,
    CHARGE_YN           BOOLEAN         NOT NULL,
    CHARGE_STATUS       SMALLINT        NOT NULL DEFAULT 0,
    NON_CHARGE_REASON   VARCHAR(30)     DEFAULT NULL,
    -- 기준정보 참조 (유형별 해당 컬럼만 사용)
    GATE_ID             VARCHAR(20)     DEFAULT NULL,
    GATE_PAIR_ID        VARCHAR(20)     DEFAULT NULL,
    ZONE_ID             VARCHAR(20)     DEFAULT NULL,
    -- 시각
    ENTER_DT            CHAR(14)        DEFAULT NULL,
    OCCUR_DT            CHAR(14)        NOT NULL,
    -- 계산 결과 (유형별 해당 컬럼만 사용)
    DIST_M              NUMERIC(12, 3)  DEFAULT NULL,
    FEE                 NUMERIC(10, 0)  DEFAULT NULL,
    SPEED_KMH           SMALLINT        DEFAULT NULL,
    SPEED_LIMIT_KMH     SMALLINT        DEFAULT NULL,
    STAY_SECONDS        INTEGER         DEFAULT NULL,
    -- 등록
    REG_DT              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_PRIM_CHARGEHAND PRIMARY KEY (TRIP_ID, CHARGE_SEQ),
    CONSTRAINT CK_PRIM_CHARGEHAND_TYPE CHECK (CHARGE_TYPE IN (0, 1, 2)),
    CONSTRAINT CK_PRIM_CHARGEHAND_PURPOSE CHECK (PURPOSE IS NULL OR PURPOSE IN (0, 1)),
    CONSTRAINT CK_PRIM_CHARGEHAND_STATUS CHECK (CHARGE_STATUS IN (0, 1))
);

COMMENT ON TABLE ROADNET.PRIM_CHARGEHAND IS
    '과금 판정 결과. RawLogWorker.h strChargeInsertSQL 스텁이 최종적으로 INSERT할 대상 테이블 (doc/README.txt A절)';
COMMENT ON COLUMN ROADNET.PRIM_CHARGEHAND.TRIP_ID IS 'PK-1. PRIM_RAWGPS.TRIP_ID 조인키';
COMMENT ON COLUMN ROADNET.PRIM_CHARGEHAND.CHARGE_SEQ IS 'PK-2. 트립 내 과금 이벤트 순번(한 트립에서 게이트/구역 여러 번 통과 가능)';
COMMENT ON COLUMN ROADNET.PRIM_CHARGEHAND.DEVICE_KEY IS 'PRIM_RAWGPS.DEVICE_KEY와 동일. 단말별 과금이력 조회용';
COMMENT ON COLUMN ROADNET.PRIM_CHARGEHAND.CHARGE_TYPE IS '0:OPEN(개방형), 1:CLOSED_ROAD(폐쇄형), 2:PARKING(주정차)';
COMMENT ON COLUMN ROADNET.PRIM_CHARGEHAND.PURPOSE IS '0:TOLL, 1:SPEED. CHARGE_TYPE=CLOSED_ROAD(1)만 사용';
COMMENT ON COLUMN ROADNET.PRIM_CHARGEHAND.CHARGE_YN IS '과금 확정 여부. FALSE면 무과금 확정(제한이내/허용구역/유예시간이내 등)';
COMMENT ON COLUMN ROADNET.PRIM_CHARGEHAND.CHARGE_STATUS IS '0:CONFIRMED(정상 확정), 1:AUDIT(세션 TTL 만료로 인한 미종결 잠정치)';
COMMENT ON COLUMN ROADNET.PRIM_CHARGEHAND.NON_CHARGE_REASON IS '무과금 사유 텍스트 (CHARGE_YN=FALSE일 때만)';
COMMENT ON COLUMN ROADNET.PRIM_CHARGEHAND.GATE_ID IS 'OPEN: 통과 게이트. CLOSED_ROAD: 진입 게이트(GATE_TYPE=CLOSED_IN) ID. PRIM_GATE_INFO.GATE_ID 조인키';
COMMENT ON COLUMN ROADNET.PRIM_CHARGEHAND.GATE_PAIR_ID IS 'CLOSED_ROAD 전용. 진입~진출 짝 키. PRIM_GATE_INFO.GATE_PAIR_ID 조인키';
COMMENT ON COLUMN ROADNET.PRIM_CHARGEHAND.ZONE_ID IS 'PARKING 전용. PRIM_PARKING_ZONE.ZONE_ID 조인키';
COMMENT ON COLUMN ROADNET.PRIM_CHARGEHAND.ENTER_DT IS
    'CLOSED_ROAD 진입시각 / PARKING 정차시작시각. CHAR(14) YYYYMMDDHH24MISS(PRIM_RAWGPS.GPS_DT와 동일 포맷). OPEN은 NULL';
COMMENT ON COLUMN ROADNET.PRIM_CHARGEHAND.OCCUR_DT IS '과금 확정 시각(OPEN=통과시각, CLOSED_ROAD=진출시각, PARKING=재개시각). CHAR(14)';
COMMENT ON COLUMN ROADNET.PRIM_CHARGEHAND.DIST_M IS 'CLOSED_ROAD 전용. 진입~진출 누적거리(m, 맵매칭 링크 경로 기준)';
COMMENT ON COLUMN ROADNET.PRIM_CHARGEHAND.FEE IS 'OPEN: FEE_AMOUNT 그대로. CLOSED_ROAD·PURPOSE=TOLL: DIST_M×FEE_PER_KM';
COMMENT ON COLUMN ROADNET.PRIM_CHARGEHAND.SPEED_KMH IS 'CLOSED_ROAD·PURPOSE=SPEED 전용. DIST_M÷소요시간 평균속도';
COMMENT ON COLUMN ROADNET.PRIM_CHARGEHAND.SPEED_LIMIT_KMH IS 'CLOSED_ROAD·PURPOSE=SPEED 전용. 판정 당시 제한속도 스냅샷';
COMMENT ON COLUMN ROADNET.PRIM_CHARGEHAND.STAY_SECONDS IS 'PARKING 전용. 체류시간(초)';

-- INDEX① 단말별 과금이력 조회 (PRIM_RAWGPS IDX①과 동일 패턴)
CREATE INDEX IF NOT EXISTS IDX_PRIM_CHARGEHAND_DEVICE_TIME
    ON ROADNET.PRIM_CHARGEHAND (DEVICE_KEY, OCCUR_DT DESC);

-- INDEX② 미종결(AUDIT) 재처리·모니터링 대상 조회
CREATE INDEX IF NOT EXISTS IDX_PRIM_CHARGEHAND_AUDIT
    ON ROADNET.PRIM_CHARGEHAND (OCCUR_DT)
    WHERE CHARGE_STATUS = 1;
