-- ROADNET DB / ROADNET 스키마 / PRIM_RAWGPS (설계서 v1.3 §2.1)
-- 사용: psql -U postgres -f roadnet/sql/roadnet.sql
--   ※ 스키마명 = DB명(ROADNET). 미따옴표 식별자는 소문자로 폴딩 → 실제명 'roadnet'
--   ※ CREATE DATABASE 는 IF NOT EXISTS 미지원 → psql \gexec 로 없을 때만 생성
--
-- PK / INDEX / 컬럼 순서 (2026-07-10)
--   PK     : (TRIP_ID, GPS_SEQ)
--   INDEX① : (DEVICE_KEY, GPS_DT DESC) — BASE_CUSTINFO 조인·단말별 GPS 이력
--   INDEX② : PENDING partial (DEVICE_KEY, TRIP_ID, GPS_DT, GPS_SEQ) — 맵매칭 Feeder
--   컬럼   : PK → INDEX 선두 → §2.1 속성 → 상태
--
-- 회원 조인:
--   PRIM_RAWGPS.DEVICE_KEY = BASE_CUSTINFO.<단말키 컬럼>
--   ※ BASE_CUSTINFO 쪽에 조인키 PK/UNIQUE INDEX 필수
--   ※ PRIM_RAWGPS 쪽은 INDEX① 선두 DEVICE_KEY 로 조인 지원 (단독 인덱스 추가 불필요)
--   FK 예 (스키마·컬럼명 확정 후):
--     ALTER TABLE ROADNET.PRIM_RAWGPS
--       ADD CONSTRAINT FK_PRIM_RAWGPS_CUST
--       FOREIGN KEY (DEVICE_KEY) REFERENCES <schema>.BASE_CUSTINFO(<pk_col>);
-- 기존 테이블 마이그레이션:
--   psql -U postgres -d roadnet -f roadnet/sql/prim_rawgps_pk_index_migrate.sql

-- DB(ROADNET) 없으면 생성, 있으면 건너뜀 (2026-07-10 최정우 추가)
SELECT 'CREATE DATABASE ROADNET'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'roadnet')\gexec

-- 생성/기존 ROADNET DB 로 접속 (실제 datname 은 소문자 폴딩된 roadnet)
\c roadnet

-- 스키마명 = DB명(ROADNET)
CREATE SCHEMA IF NOT EXISTS ROADNET;
COMMENT ON SCHEMA ROADNET IS 'RUC 위치검증·과금 (설계서 v1.3)';

SET SEARCH_PATH TO ROADNET, PUBLIC;

-- §2.1 PRIM_RAWGPS – 원시 GPS 로그 (수집서버 INSERT)
CREATE TABLE IF NOT EXISTS ROADNET.PRIM_RAWGPS (
    -- PK (운행 자연키)
    TRIP_ID         VARCHAR(60)     NOT NULL,
    GPS_SEQ         BIGINT          NOT NULL DEFAULT 0,
    -- INDEX 선두 (INDEX① DEVICE_TIME · INDEX② PENDING)
    DEVICE_KEY      VARCHAR(36)     NOT NULL,
    GPS_DT          CHAR(14)        NOT NULL,
    -- 운행·주행 상태
    TRIP_EVENT      SMALLINT        NOT NULL DEFAULT 1,
    DRIVE_STATUS    SMALLINT        NOT NULL DEFAULT 0,
    -- 좌표·맵매칭 결과
    GPS_LAT         NUMERIC(10, 6)  DEFAULT NULL,
    MATCH_LAT       NUMERIC(10, 6)  DEFAULT NULL,
    GPS_LON         NUMERIC(10, 6)  DEFAULT NULL,
    MATCH_LON       NUMERIC(10, 6)  DEFAULT NULL,
    INTERSECT_LEN   INTEGER         DEFAULT 0,
    RAW_VLD         BOOLEAN         DEFAULT FALSE,
    -- GPS 품질·센서
    SPEED_KMH       SMALLINT        DEFAULT NULL,
    HEADING         SMALLINT        DEFAULT NULL,
    ALTITUDE_M      SMALLINT        DEFAULT NULL,
    ACCURACY_M      SMALLINT        DEFAULT NULL,
    BATTERY         SMALLINT        DEFAULT NULL,
    -- 수집·처리 상태
    RECV_DT         CHAR(14)        NOT NULL DEFAULT TO_CHAR(NOW(), 'YYYYMMDDHH24MISS'),
    MATCH_LINK_ID   VARCHAR(20)     DEFAULT NULL,
    MATCH_STATUS    SMALLINT        NOT NULL DEFAULT 0,
    CONSTRAINT PK_PRIM_RAWGPS PRIMARY KEY (TRIP_ID, GPS_SEQ),
    CONSTRAINT CK_PRIM_RAWGPS_TRIP_EVENT CHECK (TRIP_EVENT IN (0, 1, 2)),
    CONSTRAINT CK_PRIM_RAWGPS_DRIVE_STATUS CHECK (DRIVE_STATUS IN (0, 1, 2, 3, 4)),
    CONSTRAINT CK_PRIM_RAWGPS_MATCH_STATUS CHECK (MATCH_STATUS IN (0, 1, 2, 3, 4))
);

COMMENT ON TABLE ROADNET.PRIM_RAWGPS IS '모바일 APP 원시 GPS. 위치검증서버가 PENDING(0) 조회 후 MATCHED(1) 갱신';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.TRIP_ID IS 'PK-1, {DEVICE_KEY}_{YYYYMMDDHH24MISS} (수집서버 START 시 적재)';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.GPS_SEQ IS 'PK-2, 운행(TRIP_ID)마다 1~N 초기화';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.DEVICE_KEY IS
    'INDEX①·② 선두. BASE_CUSTINFO 조인키(단말·회원 식별). ThreadPool sticky hash key';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.GPS_DT IS
    'INDEX①·② 구성컬럼. GPS 측정 시각 KST CHAR(14) YYYYMMDDHH24MISS';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.TRIP_EVENT IS '0:START, 1:NONE, 2:END';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.DRIVE_STATUS IS '0:ON_ROAD, 1:IDLE, 2:PARKED, 3:TUNNELING, 4:OFF_ROAD';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.GPS_LAT IS '위도 WGS-84. NULL 허용. NUMERIC(10,6) 소수 6자리';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.MATCH_LAT IS '맵매칭 위도 (위치검증서버 처리). NUMERIC(10,6) 소수 6자리';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.GPS_LON IS '경도 WGS-84. NULL 허용. NUMERIC(10,6) 소수 6자리';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.MATCH_LON IS '맵매칭 경도 (위치검증서버 처리). NUMERIC(10,6) 소수 6자리';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.INTERSECT_LEN IS 'GPS 좌표와 세그먼트 교차점까지 거리(m)';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.RAW_VLD IS
    'BOOLEAN. TRUE=맵매칭 대상. INDEX② PENDING partial 조건';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.HEADING IS
    '방위각(정북 기준 시계방향 0~359도). SMALLINT 정수, NULL 허용';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.RECV_DT IS
    '수집서버 수신 시각 CHAR(14) YYYYMMDDHH24MISS';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.MATCH_LINK_ID IS
    '맵매칭된 링크 ID (위치검증서버 처리). PRIM_LINK_INFO.LINK_ID 조인키. 매칭前/ERROR NULL';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.MATCH_STATUS IS
    '0:PENDING, 1:MATCHED, 2:PROCESSING, 3:SKIP, 4:ERROR. INDEX② PENDING partial 조건';

-- INDEX① BASE_CUSTINFO 조인·단말별 GPS 이력 (DEVICE_KEY, GPS_DT DESC)
CREATE INDEX IF NOT EXISTS IDX_PRIM_RAWGPS_DEVICE_TIME
    ON ROADNET.PRIM_RAWGPS (DEVICE_KEY, GPS_DT DESC);

-- INDEX② 맵매칭 Feeder (rawgps_select) — 필수 partial
CREATE INDEX IF NOT EXISTS IDX_PRIM_RAWGPS_PENDING
    ON ROADNET.PRIM_RAWGPS (DEVICE_KEY, TRIP_ID, GPS_DT, GPS_SEQ)
    WHERE MATCH_STATUS = 0
      AND DRIVE_STATUS <> 1
      AND RAW_VLD IS TRUE;
