-- ROADNET DB / ROADNET 스키마 / PRIM_RAWGPS (설계서 v1.3 §2.1)
-- 사용: psql -U postgres -f roadnet/sql/roadnet.sql
--   ※ 스키마명 = DB명(ROADNET). 미따옴표 식별자는 소문자로 폴딩 → 실제명 'roadnet'
--   ※ CREATE DATABASE 는 IF NOT EXISTS 미지원 → psql \gexec 로 없을 때만 생성

-- DB(ROADNET) 없으면 생성, 있으면 건너뜀 (2026-07-10 최정우 추가)
SELECT 'CREATE DATABASE ROADNET'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'roadnet')\gexec

-- 생성/기존 ROADNET DB 로 접속 (실제 datname 은 소문자 폴딩된 roadnet)
\c roadnet

-- 스키마명 = DB명(ROADNET)
CREATE SCHEMA IF NOT EXISTS ROADNET;
COMMENT ON SCHEMA ROADNET IS 'RUC 위치검증·과금 (설계서 v1.3)';

SET SEARCH_PATH TO ROADNET, PUBLIC;

-- §2.1 PRIM_RAWGPS – 원시 GPS 로그 (수집서버 INSERT)
-- 컬럼 순서: 설계서 v1.3 §2.1 표 순서
CREATE TABLE IF NOT EXISTS ROADNET.PRIM_RAWGPS (
    DEVICE_KEY      VARCHAR(36)     NOT NULL,
    GPS_DT          CHAR(14)        NOT NULL,
    GPS_SEQ         BIGINT          NOT NULL DEFAULT 0,
    TRIP_ID         VARCHAR(60)     NOT NULL,
    TRIP_EVENT      SMALLINT        NOT NULL DEFAULT 1,
    DRIVE_STATUS    SMALLINT        NOT NULL DEFAULT 0,
    GPS_LAT         NUMERIC(10, 6)  DEFAULT NULL,
    MATCH_LAT       NUMERIC(10, 6)  DEFAULT NULL,
    GPS_LON         NUMERIC(10, 6)  DEFAULT NULL,
    MATCH_LON       NUMERIC(10, 6)  DEFAULT NULL,
    INTERSECT_LEN   INTEGER         DEFAULT 0,
    RAW_VLD         BOOLEAN         DEFAULT FALSE,
    SPEED_KMH       SMALLINT        DEFAULT NULL,
    HEADING         SMALLINT        DEFAULT NULL,
    ALTITUDE_M      SMALLINT        DEFAULT NULL,
    ACCURACY_M      SMALLINT        DEFAULT NULL,
    BATTERY         SMALLINT        DEFAULT NULL,
    RECV_DT         CHAR(14)        NOT NULL DEFAULT TO_CHAR(NOW(), 'YYYYMMDDHH24MISS'),
    MATCH_STATUS    SMALLINT        NOT NULL DEFAULT 0,
    CONSTRAINT PK_PRIM_RAWGPS PRIMARY KEY (DEVICE_KEY, GPS_DT, GPS_SEQ),
    CONSTRAINT CK_PRIM_RAWGPS_TRIP_EVENT CHECK (TRIP_EVENT IN (0, 1, 2)),
    CONSTRAINT CK_PRIM_RAWGPS_DRIVE_STATUS CHECK (DRIVE_STATUS IN (0, 1, 2, 3)),
    CONSTRAINT CK_PRIM_RAWGPS_MATCH_STATUS CHECK (MATCH_STATUS IN (0, 1, 2, 3, 4))
);

COMMENT ON TABLE ROADNET.PRIM_RAWGPS IS '모바일 APP 원시 GPS. 위치검증서버가 PENDING(0) 조회 후 MATCHED(1) 갱신';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.DEVICE_KEY IS 'PK, Client Key. ThreadPool sticky hash key';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.GPS_DT IS 'PK, GPS 측정 시각 KST. CHAR(14) 고정폭, 포맷 YYYYMMDDHH24MISS(년월일시분초). 문자열 그대로 적재·비교(고정폭 zero-pad 이라 사전식 정렬=시간순)';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.GPS_SEQ IS 'PK, 운행마다 1~N 초기화';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.TRIP_ID IS 'INDEX, {DEVICE_KEY}_{YYYYMMDDHH24MISS} (수집서버 START 시 적재)';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.TRIP_EVENT IS '0:START, 1:NONE, 2:END';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.DRIVE_STATUS IS '0:ON_ROAD, 1:IDLE, 2:PARKED, 3:TUNNELING';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.GPS_LAT IS '위도 WGS-84. NULL 허용. NUMERIC(10,6) 소수 6자리';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.MATCH_LAT IS '맵매칭 위도 (위치검증서버 처리). NUMERIC(10,6) 소수 6자리';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.GPS_LON IS '경도 WGS-84. NULL 허용. NUMERIC(10,6) 소수 6자리';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.MATCH_LON IS '맵매칭 경도 (위치검증서버 처리). NUMERIC(10,6) 소수 6자리';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.INTERSECT_LEN IS '매핑 교차 거리(m)';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.RAW_VLD IS 'BOOLEAN. 원시 GPS 좌표 유효 여부. TRUE=유효(맵매칭 대상), FALSE/NULL=무효(맵매칭 제외). 기본값 FALSE. 수집서버가 좌표 유효성 판단 후 유효 시 TRUE 로 적재. 위치검증서버는 RAW_VLD IS TRUE 인 행만 조회·맵매칭';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.HEADING IS '방위각(정북 기준 시계방향 0~359도). smallint 정수, NULL 허용 (맵매칭 진행방향 판별)';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.RECV_DT IS '수집서버 수신 시각. CHAR(14) 고정폭, 포맷 YYYYMMDDHH24MISS(년월일시분초). 문자열 그대로 적재. 미지정 시 기본값 현재시각';
COMMENT ON COLUMN ROADNET.PRIM_RAWGPS.MATCH_STATUS IS '0:PENDING, 1:MATCHED, 2:PROCESSING, 3:SKIP, 4:ERROR';

CREATE INDEX IF NOT EXISTS IDX_PRIM_RAWGPS_DEVICE_KEY
    ON ROADNET.PRIM_RAWGPS (DEVICE_KEY);

CREATE INDEX IF NOT EXISTS IDX_PRIM_RAWGPS_TRIP_ID
    ON ROADNET.PRIM_RAWGPS (TRIP_ID);

CREATE INDEX IF NOT EXISTS IDX_PRIM_RAWGPS_PENDING
    ON ROADNET.PRIM_RAWGPS (DEVICE_KEY, TRIP_ID, GPS_DT, GPS_SEQ)
    WHERE MATCH_STATUS = 0;

CREATE INDEX IF NOT EXISTS IDX_PRIM_RAWGPS_DEVICE_MATCHED
    ON ROADNET.PRIM_RAWGPS (DEVICE_KEY, GPS_DT DESC)
    WHERE MATCH_STATUS = 1;

-- 권한/소유권은 환경별로 별도 관리(실서버는 DB명·앱 계정이 달라짐) — 본 생성 스크립트는
-- 순수 스키마 DDL 만 담당하고 GRANT/OWNER 구문은 포함하지 않는다. (2026-07-10 최정우)
-- 필요 시 환경별로 아래 예시처럼 접속 계정에 권한 부여:
--   GRANT USAGE ON SCHEMA ROADNET TO <app_user>;
--   GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA ROADNET TO <app_user>;
